### ISSUE TITLE
No build.gradle files

### ISSUE THREAD

**Issue by ghost** [fadelakin/SFM#1]
The project seems to be missing build.gradle file for both, the app and the root project.

**Comment by fadelakin** [comment]
That's because of the gitignore file. I can add it back in if you really need them.

**Comment by ghost** [comment]
The build.gradle files store information about project structure, dependencies (and dep versions) etc. and should be included in the repo. We received a packaging request for your app to include it in FDroid, a free/libre/opensource app repository, and I myself try to stay as close to upstream as possible, so readding the files would be quite appreciated.

**Comment by fadelakin** [comment]
Oh sorry about it. I just added everything back in so you should be all set. :+1:
